#!/usr/bin/env bash

# Static aliases

## General
alias t=' task'
alias ts=' task start'
alias td=' task done'
alias tm=' task modify'
alias ty=' task sync'

## TaskWarrior context
alias tp=' task context personal'
alias tn=' task context none'
alias tw=' task context trabajo'
alias ta=' task add project:personal'
alias taw=' task add project:trabajo'

# Dynamic aliases
## task start
for (( i = 1; i < 100; i++ )); do
    alias "ts${i}"=" task ${i} start"
    alias "t${i}s"=" task ${i} start"
done

## task stop
for (( i = 1; i < 100; i++ )); do
    alias "tp${i}"=" task ${i} stop"
    alias "t${i}p"=" task ${i} stop"
done

## task modify
for (( i = 1; i < 100; i++ )); do
    alias "tm${i}"=" task ${i} modify"
    alias "t${i}m"=" task ${i} modify"
done

## task done
for (( i = 1; i < 100; i++ )); do
    alias "td${i}"=" task ${i} done"
    alias "t${i}d"=" task ${i} done"
done
