# Send extended keys (make Ctrl+Enter/Shift+Enter and others work)
set -g extended-keys always
set -g extended-keys-format csi-u

# Tell tmux that some terminals have more features
set -as terminal-features 'xterm-256color:extkeys:focus:ccolour:usstyle'
