# ---------------------------------------------------
# Copyright (c) 2013 Pablo Caro. All Rights Reserved.
# Pablo Caro <me@pcaro.es> - http://pcaro.es/
# bashrc
# ---------------------------------------------------

# If not running interactively, exit
[[ $- != *i* ]] && return

# Vim as system editor
export EDITOR=vim

# History length
export HISTSIZE=2000

# Set TERM var correctly WARNING
export TERM=xterm-256color

# Aliases
if [ -f ~/.bash_alias ] ; then
    . ~/.bash_alias
fi
