#!/bin/bash

mount_point=$DIR

used=$(df $mount_point | tail -1 | awk '{print $5}' | head -c -2)

# Full text
echo "$used%"

# Short text
echo "$used%"

if [ $used -ge 80 ] ; then
    echo "#F07178"
elif [ $used -ge 50 ] ; then
    echo "#FFCB6B"
else
    echo "#C3E88D"
fi
