format = '$shell$hostname$directory$fill$all$line_break$character'

[shell]
format = '$indicator'
fish_indicator = '\[[󰈺 ]($style)\]'
zsh_indicator = ''
style = 'cyan bold'
disabled = false

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[hostname]
ssh_only = false
format = '\[[$hostname]($style)\] '
style = "bold yellow"

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '\[ [$symbol$branch(:$remote_branch)]($style) '

[git_status]
untracked = 'U'
up_to_date = ''
format = '[$all_status$ahead_behind]($style)\]'

[package]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})]($style)([ \($virtualenv\)](red bold))\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
