#!/bin/bash

used=$(free | sed -n '2p' | awk '{printf "%.0f", (1 - ($7 / $2)) * 100}')

# Full text
echo "$used%"

# Short text
echo "$used%"

if [ $used -ge 80 ] ; then
    echo "#F07178"
elif [ $used -ge 50 ] ; then
    echo "#FFCB6B"
else
    echo "#C3E88D"
fi
