#!/bin/bash

OUT=''

CONTEXT_INFO=$(task context show)
echo $CONTEXT_INFO | grep -q 'No context'

if [ $? -eq 0 ] ; then
    CONTEXT='none'
else
    CONTEXT=$(echo $CONTEXT_INFO | awk '{print $2}' | cut -d"'" -f2)
    OUT="$OUT [$CONTEXT]"
fi

COUNT_TODAY=$(task due:today status:pending count)
if [ $COUNT_TODAY -gt 0 ] ; then
    OUT="$OUT [$COUNT_TODAY]"
else
    OUT="$OUT []"
fi

NEXT=$(task i3blocks | sed -n '4p')
OUT="$OUT $NEXT"

echo $OUT
