#!/bin/sh
# ~/.xinitrc

# Use Caps Lock as LShift (which then will be modified using xcape)
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 66 = Shift_L'

HOSTNAME=$(hostname -s)
cat $HOME/dotfiles/i3/config.base > $HOME/.i3/config
cat $HOME/dotfiles/i3/config.$HOSTNAME >> $HOME/.i3/config
cat $HOME/dotfiles/i3/i3blocks/config.$HOSTNAME > $HOME/.i3/i3blocks/config

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

case $1 in
    *) exec i3 ;;
    # *) exec i3 -V > ~/.i3/i3log 2>&1;;
    # *) exec xterm;;
esac
