# ---------------------------------------------------
# Copyright (c) 2013 Pablo Caro. All Rights Reserved.
# Pablo Caro <me@pcaro.es> - http://pcaro.es/
# bashrc
# ---------------------------------------------------

# Extend path
export PATH=$PATH:~/bin

# Vim as system editor
export EDITOR=vim

# History length
export HISTSIZE=2000

# Aliases
if [ -f ~/.bash_alias ] ; then
    . ~/.bash_alias
fi
